# -*- coding: utf-8 -*-
"""과제_전성민.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0vbuKGJwWQ3QKKg39sMPxASgrWuL1r-

#0. matplotlib 그래프에 한글 사용 (설치하지 않으면 한글깨짐)
설치 후, 런타임 재시작 필요
"""

#matplotlib 그래프 사용시, 한글폰트 설치
#설치하지 않으면 한글깨짐
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

"""#1. 문제 정의
* 목표 정의 및 가설수립

##1.1 목표
1. 두집단의 중도탈락의도, 학업스트레스, 사회적지지, 자기효능감, 대학만족에 대한 t-검정 실시한 후 분석과 결과에 대한 의미를 작성
     * 남학생 vs 여학생, 저학년(1,2학년) vs 고학년 (3학년 이상)
2. 모든 변수 (중도탈락의도, 학업스트레스, 사회적지지, 자기효능감, 대학만족) 간 피어슨 상관분석을 실시한 후 분석 결과의 의미를 작성

##1.2 가설 수립
#### 1.2.1 평균 검증
- 귀무가설 (H0) : 중도탈락의도, 학업스트레스, 사회적지지도, 자기효능감, 대학만족 은 남학생/여학생, 저학년/고학년 간 (평균이) 동일할 것이다
- 대립가설 (H1) : 중도탈락의도, 학업스트레스, 사회적지지도, 자기효능감, 대학만족 은 남학생/여학생, 저학년/고학년 간 (평균이) 동일하지 않을 것이다
---
#### 1.2.2 상관 분석
- 귀무가설 (H0) : 중도탈락의도, 학업스트레스, 사회적지지도, 자기효능감, 대학만족 은 상호관계가 독립적일 것이다
- 대립가설 (H1) : 중도탈락의도, 학업스트레스, 사회적지지도, 자기효능감, 대학만족 은 상호관계가 독립적이지 않을 것이다
---
#### 1.2.3 유의 수준 (p-value) : 0.05

# 2. 데이터프레임 구성
*   라이브러리 로딩 및 데이터 불러오기

##2.1 라이브러디 로딩
"""

# 라이브러리
import pandas as pd #데이터 프레임
import scipy.stats as stats  #통계 라이브러리
import matplotlib.pyplot as plt #차팅
import seaborn as sns #차팅
import warnings

plt.rc('font', family='NanumBarunGothic') #한글 폰트
warnings.filterwarnings('ignore') #Warning 무시





"""##2.2 분석 소스 데이터 셋 불러오기"""

#과제 데이터를 깃허브에 올려놓고 판다스로 읽음, 한글이 들어 있어 한글깨지지 않게 인코딩 함

data = pd.read_csv("https://raw.githubusercontent.com/junixs/assignment/main/data.csv", encoding='cp949')

data

"""# 3. 데이터 전처리
* 남학생 vs 여학생
* 저학년 (1,2학년) vs 고학년 (3학년이상)

##3.1 남학생 vs 여학생
"""

#남학생 데이터 추출
#원본 데이터에서 남학생 데이터만 필터링하여 male에 저장

male = data[data['성별'] == '남성']

#남학생 데이터 확인

male



#여학생 데이터 추출
#원본 데이터에서 여학생 데이터만 필터링하여 female에 저장

female = data[data['성별'] == '여성']

#여학생 데이터 확인

female



"""##3.2. 저학년 (1,2학년) vs 고학년 (3학년이상)"""

#저학년 (1,2학년) 데이터 추출
#원본 데이터에서 저학년 (1,2학년) 데이터만 필터링하여 lowclass에 저장

lowclass = data[(data['학년'] == 1) | (data['학년'] == 2)]

#저학년 데이터 확인

lowclass

#고학년 (3학년이상)
#원본 데이터에서 고학년 (3학년이상) 데이터만 필터링하여 highclass에 저장

highclass = data[data['학년'] >= 3]

#고학년 데이터 확인

highclass

"""#3. 데이터 탐색

###3.1 기술 통계량 확인
"""

#남학생 데이터에 대한 기술통계량 살펴보기

male[['학업스트레스','사회적지지','자기효능감','중도탈락의도','대학만족']].describe()

#여학생 데이터에 대한 기술통계량 살펴보기

female[['학업스트레스','사회적지지','자기효능감','중도탈락의도','대학만족']].describe()

#저학년 데이터에 대한 기술통계량 살펴보기

lowclass[['학업스트레스','사회적지지','자기효능감','중도탈락의도','대학만족']].describe()

#고학년 데이터에 대한 기술통계량 살펴보기

highclass[['학업스트레스','사회적지지','자기효능감','중도탈락의도','대학만족']].describe()

"""##3.1 평균 시각화 (평균값을 점으로 표현하고 평균에 대한 95% 신뢰구간)"""

sns.catplot(x='성별', y='학업스트레스', kind='point', data=data)
sns.catplot(x='학년', y='학업스트레스', kind='point', data=data)
sns.catplot(x='성별', y='사회적지지', kind='point', data=data)
sns.catplot(x='학년', y='사회적지지', kind='point', data=data)
sns.catplot(x='성별', y='자기효능감', kind='point', data=data)
sns.catplot(x='학년', y='자기효능감', kind='point', data=data)
sns.catplot(x='성별', y='중도탈락의도', kind='point', data=data)
sns.catplot(x='학년', y='중도탈락의도', kind='point', data=data)
sns.catplot(x='성별', y='대학만족', kind='point', data=data)
sns.catplot(x='학년', y='대학만족', kind='point', data=data)

"""##3.2 빈도 시각화

###성별
"""

sns.catplot(x='학업스트레스',
            col='성별',   # 캔버스 분리하기
            kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='사회적지지',
            col='성별',   # 캔버스 분리하기
            kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='자기효능감',
            col='성별',   # 캔버스 분리하기
            kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='중도탈락의도',
            col='성별',   # 캔버스 분리하기
            kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='대학만족',
            col='성별',   # 캔버스 분리하기
             kind='count', # 빈도 막대그래프 그리기
            data=data)

"""###학년별"""

sns.catplot(x='학업스트레스',
            col='학년',   # 캔버스 분리하기
             kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='사회적지지',
            col='학년',   # 캔버스 분리하기
             kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='자기효능감',
            col='학년',   # 캔버스 분리하기
             kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='중도탈락의도',
            col='학년',   # 캔버스 분리하기
             kind='count', # 빈도 막대그래프 그리기
            data=data)
sns.catplot(x='대학만족',
            col='학년',   # 캔버스 분리하기
             kind='count', # 빈도 막대그래프 그리기
            data=data)

"""##3.3 상관관계 시각화"""

sns.pairplot(data[['학업스트레스','사회적지지','자기효능감','중도탈락의도','대학만족']],
             diag_kind='hist')
plt.show()

"""#4. 독립표본 t-검정 실시
* 남학생 vs 여학생
* 저학년 (1,2학년) vs 고학년 (3학년이상)

##4.1. 남학생 vs 여학생
"""

print('남학생 vs 여학생 학업스트레스 t-test 결과:', stats.ttest_ind(male['학업스트레스'], female['학업스트레스'], equal_var=True))
print('남학생 vs 여학생 사회적지지   t-test 결과:', stats.ttest_ind(male['사회적지지'], female['사회적지지'], equal_var=True))
print('남학생 vs 여학생 자기효능감   t-test 결과:', stats.ttest_ind(male['자기효능감'], female['자기효능감'], equal_var=True))
print('남학생 vs 여학생 중도탈락의도 t-test 결과:', stats.ttest_ind(male['중도탈락의도'], female['중도탈락의도'], equal_var=True))
print('남학생 vs 여학생 대학만족     t-test 결과:', stats.ttest_ind(male['대학만족'], female['대학만족'], equal_var=True))

"""##4.2. 저학년 (1,2학년) vs 고학년 (3학년이상)"""

print('저학년 vs 고학년 학업스트레스 t-test 결과:', stats.ttest_ind(lowclass['학업스트레스'], highclass['학업스트레스'], equal_var=True))
print('저학년 vs 고학년 사회적지지   t-test 결과:', stats.ttest_ind(lowclass['사회적지지'], highclass['사회적지지'], equal_var=True))
print('저학년 vs 고학년 자기효능감   t-test 결과:', stats.ttest_ind(lowclass['자기효능감'], highclass['자기효능감'], equal_var=True))
print('저학년 vs 고학년 중도탈락의도 t-test 결과:', stats.ttest_ind(lowclass['중도탈락의도'], highclass['중도탈락의도'], equal_var=True))
print('저학년 vs 고학년 대학만족     t-test 결과:', stats.ttest_ind(lowclass['대학만족'], highclass['대학만족'], equal_var=True))

"""#5. 피어슨 상관분석 실시"""

print('학업스트레스-사회적지지 상관분석 결과:   ', stats.pearsonr(data.학업스트레스.values, data.사회적지지.values))
print('학업스트레스-자기효능감 상관분석 결과:   ',stats.pearsonr(data.학업스트레스.values, data.자기효능감.values))
print('학업스트레스-중도탈락의도 상관분석 결과: ',stats.pearsonr(data.학업스트레스.values, data.중도탈락의도.values))
print('학업스트레스-대학만족 상관분석 결과:     ',stats.pearsonr(data.학업스트레스.values, data.대학만족.values))
print('사회적지지-자기효능감 상관분석 결과:     ',stats.pearsonr(data.사회적지지.values, data.자기효능감.values))
print('사회적지지-중도탈락의도 상관분석 결과:   ',stats.pearsonr(data.사회적지지.values, data.중도탈락의도.values))
print('사회적지지-대학만족 상관분석 결과:       ',stats.pearsonr(data.사회적지지.values, data.대학만족.values))
print('자기효능감-중도탈락의도 상관분석 결과:   ',stats.pearsonr(data.자기효능감.values, data.중도탈락의도.values))
print('자기효능감-대학만족 상관분석 결과:       ',stats.pearsonr(data.자기효능감.values, data.대학만족.values))
print('중도탈락의도-대학만족 상관분석 결과:     ',stats.pearsonr(data.중도탈락의도.values, data.대학만족.values))